"""
scripts/prepare_colab.py
=========================
Assembles the clean/upload/ folder for Google Colab training.

IMPORTANT — Parity guarantee:
  This script copies scripts/03_train.py directly into the upload bundle
  rather than duplicating its logic. This ensures Colab training uses the
  exact same code as local training. If you change 03_train.py, simply
  re-run this script to propagate the changes.

Run this locally whenever you want to retrain, then upload the
resulting folder to the root of your Google Drive.

What it copies:
  • data/X_seq.pkl, G_seq.pkl, player_ids.pkl,
         player_id2team.pkl, player_id2position.pkl
  • scripts/03_train.py     (the canonical training script)
  • gatv2tcn.py + tcn.py    (from GATV2_SRC)
  • config.py               (auto-generated Colab shim)
  • train.ipynb             (minimal Colab bootstrap notebook)

Upload workflow:
  1. python scripts/prepare_colab.py
  2. Upload clean/upload/ to the root of your Google Drive
  3. Open upload/train.ipynb in Colab → Runtime → Run all
  4. When done, download clean_download/ from your Google Drive
  5. Copy model.pth / team_emb.pth / pos_emb.pth → clean/models/<ACTIVE_MODEL>/
  6. Run: python scripts/04_calibrate.py
"""
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from config import (DATA_DIR, GATV2_SRC, FEATURE_COLS, PREDICTION_COLS,
                    SEQ_LENGTH, ACTIVE_MODEL, QUANTILE_REGRESSION, QUANTILES,
                    SPLIT_TRAIN, SPLIT_VAL)

UPLOAD_DIR   = ROOT / "upload"
DATA_OUT     = UPLOAD_DIR / "data"
SCRIPTS_OUT  = UPLOAD_DIR / "scripts"

# ── Data files required by 03_train.py ────────────────────────────
REQUIRED_DATA = [
    "X_seq.pkl",
    "G_seq.pkl",
    "player_ids.pkl",
    "player_id2team.pkl",
    "player_id2position.pkl",
]

# ── Model source files ────────────────────────────────────────────
REQUIRED_SRC = [
    "gatv2tcn.py",
    "tcn.py",
]


def check_files():
    missing = []
    for f in REQUIRED_DATA:
        if not (DATA_DIR / f).exists():
            missing.append(str(DATA_DIR / f))
    for f in REQUIRED_SRC:
        if not (GATV2_SRC / f).exists():
            missing.append(str(GATV2_SRC / f))
    train_script = ROOT / "scripts" / "03_train.py"
    if not train_script.exists():
        missing.append(str(train_script))
    if missing:
        print("ERROR: Missing required files:")
        for m in missing:
            print(f"  {m}")
        print("\nRun scripts/02_build_tensors.py first.")
        sys.exit(1)


def copy_files():
    # Clear previous upload folder
    if UPLOAD_DIR.exists():
        shutil.rmtree(UPLOAD_DIR)
    DATA_OUT.mkdir(parents=True)
    SCRIPTS_OUT.mkdir(parents=True)

    # Data
    total_mb = 0.0
    for f in REQUIRED_DATA:
        src = DATA_DIR / f
        shutil.copy2(src, DATA_OUT / f)
        mb = src.stat().st_size / 1e6
        total_mb += mb
        print(f"  ✓ data/{f}  ({mb:.1f} MB)")

    # Training script — THE canonical copy, ensuring parity
    train_src = ROOT / "scripts" / "03_train.py"
    shutil.copy2(train_src, SCRIPTS_OUT / "03_train.py")
    print(f"  ✓ scripts/03_train.py  (canonical training script)")

    # Model source
    for f in REQUIRED_SRC:
        src = GATV2_SRC / f
        shutil.copy2(src, UPLOAD_DIR / f)
        print(f"  ✓ {f}")

    print(f"\n  Total data size: {total_mb:.1f} MB")
    return total_mb


def write_config_shim():
    """Write a Colab-specific config.py that mirrors clean/config.py
    but with Drive-appropriate paths."""
    config_path = UPLOAD_DIR / "config.py"
    content = f'''\
"""
config.py — Colab shim (auto-generated by prepare_colab.py)

This mirrors clean/config.py but with Google Drive paths.
DO NOT EDIT — re-run prepare_colab.py to regenerate.
"""
from pathlib import Path

ACTIVE_MODEL = "{ACTIVE_MODEL}"

# Paths resolve to Google Drive
ROOT         = Path(__file__).resolve().parent
DATA_DIR     = ROOT / "data"
MODEL_DIR    = Path("/content/drive/MyDrive/ballnet/{ACTIVE_MODEL}/clean_download")
GATV2_SRC    = ROOT   # gatv2tcn.py lives in upload root

FEATURE_COLS    = {FEATURE_COLS!r}
PREDICTION_COLS = {PREDICTION_COLS!r}
PRED_INDICES    = [FEATURE_COLS.index(c) for c in PREDICTION_COLS]
SEQ_LENGTH      = {SEQ_LENGTH}

QUANTILE_REGRESSION = {QUANTILE_REGRESSION}
QUANTILES = {QUANTILES!r}

SPLIT_TRAIN = {SPLIT_TRAIN}
SPLIT_VAL   = {SPLIT_VAL}
'''
    config_path.write_text(content)
    print(f"  ✓ config.py  (Colab path shim)")


def write_notebook():
    """Write a minimal Colab notebook that bootstraps and runs 03_train.py."""
    nb_path = UPLOAD_DIR / "train.ipynb"
    cells = []

    def code_cell(source: str):
        cells.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": source.strip()
        })

    def md_cell(source: str):
        cells.append({
            "cell_type": "markdown",
            "metadata": {},
            "source": source.strip()
        })

    # ── Cell 1: Mount Drive ───────────────────────────────────────
    md_cell("## Step 1 — Mount Google Drive")
    code_cell("""\
from google.colab import drive
drive.mount('/content/drive')
""")

    # ── Cell 2: Install deps ──────────────────────────────────────
    md_cell("## Step 2 — Install dependencies")
    code_cell("""\
!pip install -q torch torchvision torch-geometric networkx tqdm scikit-learn
""")

    # ── Cell 3: Setup + Train ─────────────────────────────────────
    md_cell("""\
## Step 3 — Train

This cell runs `scripts/03_train.py` — the **exact same** training script used
locally. Changes to `03_train.py` are automatically reflected here via
`prepare_colab.py`.""")
    code_cell(f"""\
import os, subprocess, sys

DRIVE_ROOT   = '/content/drive/MyDrive/ballnet/{ACTIVE_MODEL}'
UPLOAD_DIR   = os.path.join(DRIVE_ROOT, 'upload')
DOWNLOAD_DIR = os.path.join(DRIVE_ROOT, 'clean_download')

os.makedirs(DOWNLOAD_DIR, exist_ok=True)

# Use Popen to manually pipe the output
process = subprocess.Popen(
    ['python', '-u', 'scripts/03_train.py'],
    cwd=UPLOAD_DIR,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT, # Merges stderr into stdout
    text=True
)

# Stream the output line-by-line
for line in process.stdout:
    print(line, end='')

process.wait()

print(f'\\nExit code: {{process.returncode}}')
print(f'Model weights saved to: {{DOWNLOAD_DIR}}/')
""")

    # ── Cell 4: Verify ────────────────────────────────────────────
    md_cell("## Step 4 — Verify output")
    code_cell(f"""\
import os
DOWNLOAD_DIR = '/content/drive/MyDrive/ballnet/{ACTIVE_MODEL}/clean_download'
expected = ['model.pth', 'team_emb.pth', 'pos_emb.pth', 'train_loss.npy', 'val_loss.npy']
for f in expected:
    path = os.path.join(DOWNLOAD_DIR, f)
    if os.path.exists(path):
        size_kb = os.path.getsize(path) / 1024
        print(f'  ✓ {{f}}  ({{size_kb:.1f}} KB)')
    else:
        print(f'  ✗ {{f}}  MISSING')
print(f'\\nDone! Copy these files to clean/models/{ACTIVE_MODEL}/')
print('Then run: python scripts/04_calibrate.py')
""")

    # ── Write the notebook JSON ───────────────────────────────────
    import json
    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {"name": "python", "version": "3.10.0"},
            "colab": {"provenance": []}
        },
        "cells": cells
    }
    with open(nb_path, "w") as f:
        json.dump(notebook, f, indent=1)
    print(f"  ✓ train.ipynb")


def main():
    print("Checking required files...")
    check_files()
    print(f"\nCopying files to {UPLOAD_DIR}/")
    total_mb = copy_files()
    print("\nGenerating Colab config shim...")
    write_config_shim()
    print("\nGenerating notebook...")
    write_notebook()
    print(f"\n{'='*55}")
    print(f"Upload folder ready: {UPLOAD_DIR}")
    print(f"Total size: ~{total_mb:.0f} MB")
    print(f"\nNext steps:")
    print(f"  1. Upload the 'upload/' folder to the ROOT of your Google Drive")
    print(f"  2. Open upload/train.ipynb in Google Colab")
    print(f"  3. Runtime → Run all  (~15-30 min on T4/A100)")
    print(f"  4. Download 'clean_download/' folder from Google Drive")
    print(f"  5. Copy model.pth / team_emb.pth / pos_emb.pth → clean/models/{ACTIVE_MODEL}/")
    print(f"  6. Run: python scripts/04_calibrate.py")
    print(f"{'='*55}")


if __name__ == "__main__":
    main()
