import type { StatDefinition } from "./types";

export const BACKFIELD_STATS: StatDefinition[] = [
  {
    id: "rushing_epa",
    label: "Rushing EPA",
    section: "Efficiency",
    kind: "continuous",
    higherIsBetter: true,
    format: "one_decimal",
    xMin: -20,
    xMax: 20,
    minNBase: 5,
    denom: "carries",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "low",
  },
  {
    id: "ryoe",
    label: "Rush Yards Over Expected",
    section: "Efficiency",
    kind: "continuous",
    higherIsBetter: true,
    format: "one_decimal",
    xMin: -10,
    xMax: 15,
    minNBase: 1,
    denom: "NGS week",
    source: "NGS rush_yards_over_expected",
    startYear: 2016,
    zeroMass: "low",
  },
  {
    id: "yards_per_carry",
    label: "Yards per Carry",
    section: "Efficiency",
    kind: "continuous",
    higherIsBetter: true,
    format: "two_decimal",
    xMin: -5,
    xMax: 20,
    minNBase: 5,
    denom: "carries",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "low",
  },
  {
    id: "yards_after_contact",
    label: "Yards After Contact",
    section: "Elusiveness",
    kind: "continuous",
    higherIsBetter: true,
    format: "yards",
    xMin: 0,
    xMax: 175,
    lowerBound: 0,
    minNBase: 5,
    denom: "carries",
    source: "PFR rush",
    startYear: 2018,
    zeroMass: "med",
  },
  {
    id: "broken_tackles",
    label: "Broken Tackles",
    section: "Elusiveness",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 16,
    binWidth: 1,
    minNBase: 5,
    denom: "carries",
    source: "pfr_advstats rush",
    startYear: 2018,
    zeroMass: "high",
  },
  {
    id: "ngs_efficiency",
    label: "NGS Efficiency",
    section: "NGS",
    kind: "continuous",
    higherIsBetter: true,
    format: "ratio",
    xMin: 0,
    xMax: 8,
    lowerBound: 0,
    minNBase: 1,
    denom: "NGS week",
    source: "NGS efficiency",
    startYear: 2016,
    zeroMass: "none",
  },
  {
    id: "expected_rush_yards",
    label: "Expected Rush Yards",
    section: "NGS",
    kind: "continuous",
    higherIsBetter: true,
    format: "yards",
    xMin: 0,
    xMax: 200,
    lowerBound: 0,
    minNBase: 1,
    denom: "NGS week",
    source: "NGS",
    startYear: 2016,
    zeroMass: "none",
  },
  {
    id: "time_to_los",
    label: "Time to Line of Scrimmage",
    section: "NGS",
    kind: "continuous",
    higherIsBetter: false,
    format: "seconds",
    xMin: 1.5,
    xMax: 5,
    lowerBound: 1.5,
    minNBase: 1,
    denom: "NGS rush week",
    source: "NGS rushing",
    startYear: 2016,
    zeroMass: "none",
  },
  {
    id: "eight_plus_defenders_pct",
    label: "8+ Defenders %",
    section: "NGS",
    kind: "continuous",
    higherIsBetter: true,
    format: "percent",
    xMin: 0,
    xMax: 1,
    lowerBound: 0,
    upperBound: 1,
    minNBase: 1,
    denom: "NGS week",
    source: "NGS",
    startYear: 2016,
    zeroMass: "low",
  },
  {
    id: "rushing_tds",
    label: "Rushing TDs",
    section: "Production",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 6,
    binWidth: 1,
    minNBase: 1,
    denom: "games with carries",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "fumbles",
    label: "Fumbles",
    section: "Production",
    kind: "discrete",
    higherIsBetter: false,
    format: "count",
    xMin: 0,
    xMax: 7,
    binWidth: 1,
    minNBase: 1,
    denom: "touches",
    source: "rushing_fumbles",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "rush_attempts",
    label: "Rush Attempts",
    section: "Volume",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 45,
    binWidth: 1,
    minNBase: 5,
    denom: "carries",
    source: "player_stats.carries",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "rushing_yards",
    label: "Rushing Yards",
    section: "Volume",
    kind: "continuous",
    higherIsBetter: true,
    format: "yards",
    xMin: -15,
    xMax: 296,
    lowerBound: 0,
    minNBase: 5,
    denom: "carries",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "targets",
    label: "Targets",
    section: "Receiving",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 15,
    binWidth: 1,
    minNBase: 2,
    denom: "targets",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "receptions",
    label: "Receptions",
    section: "Receiving",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 12,
    binWidth: 1,
    minNBase: 2,
    denom: "targets",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "receiving_yards",
    label: "Receiving Yards",
    section: "Receiving",
    kind: "continuous",
    higherIsBetter: true,
    format: "yards",
    xMin: -10,
    xMax: 150,
    lowerBound: 0,
    minNBase: 2,
    denom: "targets",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "target_share",
    label: "Target Share",
    section: "Opportunity",
    kind: "continuous",
    higherIsBetter: true,
    format: "percent",
    xMin: 0,
    xMax: 0.4,
    lowerBound: 0,
    upperBound: 0.4,
    minNBase: 2,
    denom: "team targets",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "wopr",
    label: "WOPR",
    section: "Opportunity",
    kind: "continuous",
    higherIsBetter: true,
    format: "ratio",
    xMin: 0,
    xMax: 0.5,
    lowerBound: 0,
    minNBase: 2,
    denom: "targets",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "red_zone_touches",
    label: "Red Zone Touches",
    section: "Opportunity",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 12,
    binWidth: 1,
    minNBase: 1,
    denom: "games",
    source: "pbp",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "expected_fantasy_points",
    label: "Expected Fantasy Points",
    section: "Opportunity",
    kind: "continuous",
    higherIsBetter: true,
    format: "one_decimal",
    xMin: 0,
    xMax: 40,
    lowerBound: 0,
    minNBase: 1,
    denom: "games",
    source: "ff_opportunity",
    startYear: 2006,
    zeroMass: "low",
  },
  {
    id: "offensive_snap_pct",
    label: "Offensive Snap %",
    section: "Usage",
    kind: "continuous",
    higherIsBetter: true,
    format: "percent",
    xMin: 0,
    xMax: 1,
    lowerBound: 0,
    upperBound: 1,
    minNBase: 1,
    denom: "offensive snaps",
    source: "snap_counts",
    startYear: 2012,
    zeroMass: "low",
  },
];
