import type { StatDefinition } from "./types";

export const DEF_FRONT_STATS: StatDefinition[] = [
  {
    id: "pressures",
    label: "Pressures",
    section: "Pass rush",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 15,
    binWidth: 1,
    minNBase: 1,
    denom: "games",
    source: "pfr_advstats def",
    startYear: 2018,
    zeroMass: "high",
  },
  {
    id: "qb_hits",
    label: "QB Hits",
    section: "Pass rush",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 12,
    binWidth: 1,
    minNBase: 1,
    denom: "games",
    source: "def_qb_hits",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "hurries",
    label: "Hurries",
    section: "Pass rush",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 10,
    binWidth: 1,
    minNBase: 1,
    denom: "games",
    source: "PFR def",
    startYear: 2018,
    zeroMass: "high",
  },
  {
    id: "sacks",
    label: "Sacks",
    section: "Pass rush",
    kind: "discrete",
    higherIsBetter: true,
    format: "one_decimal",
    xMin: 0,
    xMax: 7,
    binWidth: 0.5,
    minNBase: 1,
    denom: "games",
    source: "def_sacks",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "tackles_for_loss",
    label: "Tackles for Loss",
    section: "Pass rush",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 6,
    binWidth: 1,
    minNBase: 1,
    denom: "games",
    source: "def_tackles_for_loss",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "missed_tackle_rate",
    label: "Missed Tackle Rate",
    section: "Tackles",
    kind: "continuous",
    higherIsBetter: false,
    format: "percent",
    xMin: 0,
    xMax: 1,
    lowerBound: 0,
    upperBound: 1,
    minNBase: 1,
    denom: "tackle_chances",
    source: "missed_tackles / (tackles_combined + missed_tackles)",
    startYear: 2018,
    zeroMass: "high",
  },
  {
    id: "missed_tackles",
    label: "Missed Tackles",
    section: "Tackles",
    kind: "discrete",
    higherIsBetter: false,
    format: "count",
    xMin: 0,
    xMax: 7,
    binWidth: 1,
    minNBase: 1,
    denom: "games",
    source: "PFR def_missed_tackles",
    startYear: 2018,
    zeroMass: "high",
  },
  {
    id: "tackles_combined",
    label: "Combined Tackles",
    section: "Tackles",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 24,
    binWidth: 1,
    minNBase: 1,
    denom: "games",
    source: "def_tackles_combined",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "tackles_solo",
    label: "Solo Tackles",
    section: "Tackles",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 16,
    binWidth: 1,
    minNBase: 1,
    denom: "games",
    source: "def_tackles_solo",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "tackles_ast",
    label: "Assisted Tackles",
    section: "Tackles",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 12,
    binWidth: 1,
    minNBase: 1,
    denom: "games",
    source: "def_tackle_assists",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "forced_fumbles",
    label: "Forced Fumbles",
    section: "Ball",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 4,
    binWidth: 1,
    minNBase: 1,
    denom: "games",
    source: "def_fumbles_forced",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "interceptions",
    label: "Interceptions",
    section: "Ball",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 3,
    binWidth: 1,
    minNBase: 1,
    denom: "games",
    source: "def_interceptions",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "defensive_snap_pct",
    label: "Defensive Snap %",
    section: "Usage",
    kind: "continuous",
    higherIsBetter: true,
    format: "percent",
    xMin: 0,
    xMax: 1,
    lowerBound: 0,
    upperBound: 1,
    minNBase: 1,
    denom: "defensive snaps",
    source: "snap_counts.defense_pct",
    startYear: 2012,
    zeroMass: "low",
  },
];
