import type { StatDefinition } from "./types";

export const PASS_CATCHER_STATS: StatDefinition[] = [
  {
    id: "targets",
    label: "Targets",
    section: "Volume",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 21,
    binWidth: 1,
    minNBase: 3,
    denom: "targets",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "receptions",
    label: "Receptions",
    section: "Volume",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 21,
    binWidth: 1,
    minNBase: 3,
    denom: "targets",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "receiving_yards",
    label: "Receiving Yards",
    section: "Volume",
    kind: "continuous",
    higherIsBetter: true,
    format: "yards",
    xMin: -10,
    xMax: 336,
    lowerBound: 0,
    minNBase: 3,
    denom: "targets",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "receiving_tds",
    label: "Receiving TDs",
    section: "Scoring",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 5,
    binWidth: 1,
    minNBase: 1,
    denom: "games",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "drops",
    label: "Drops",
    section: "Ball security",
    kind: "discrete",
    higherIsBetter: false,
    format: "count",
    xMin: 0,
    xMax: 5,
    binWidth: 1,
    minNBase: 3,
    denom: "targets",
    source: "PFR rec / FTN is_drop",
    startYear: 2018,
    zeroMass: "high",
  },
  {
    id: "yac",
    label: "Yards After Catch",
    section: "YAC",
    kind: "continuous",
    higherIsBetter: true,
    format: "yards",
    xMin: 0,
    xMax: 175,
    lowerBound: 0,
    minNBase: 2,
    denom: "receptions",
    source: "receiving_yards_after_catch",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "avg_yac",
    label: "Average YAC",
    section: "YAC",
    kind: "continuous",
    higherIsBetter: true,
    format: "one_decimal",
    xMin: 0,
    xMax: 20,
    lowerBound: 0,
    minNBase: 1,
    denom: "NGS receiving week",
    source: "NGS receiving",
    startYear: 2016,
    zeroMass: "none",
  },
  {
    id: "expected_yac",
    label: "Expected YAC",
    section: "YAC",
    kind: "continuous",
    higherIsBetter: true,
    format: "one_decimal",
    xMin: 0,
    xMax: 20,
    lowerBound: 0,
    minNBase: 1,
    denom: "NGS week",
    source: "NGS avg_expected_yac",
    startYear: 2016,
    zeroMass: "none",
  },
  {
    id: "yac_oe",
    label: "YAC Over Expected",
    section: "YAC",
    kind: "continuous",
    higherIsBetter: true,
    format: "one_decimal",
    xMin: -8,
    xMax: 8,
    minNBase: 1,
    denom: "NGS week",
    source: "NGS avg_yac_above_expectation",
    startYear: 2016,
    zeroMass: "none",
  },
  {
    id: "separation",
    label: "Separation",
    section: "NGS",
    kind: "continuous",
    higherIsBetter: true,
    format: "one_decimal",
    xMin: 0,
    xMax: 9,
    lowerBound: 0,
    minNBase: 1,
    denom: "NGS week",
    source: "NGS avg_separation",
    startYear: 2016,
    zeroMass: "none",
  },
  {
    id: "cushion",
    label: "Cushion",
    section: "NGS",
    kind: "continuous",
    higherIsBetter: true,
    format: "one_decimal",
    xMin: 0,
    xMax: 15,
    lowerBound: 0,
    minNBase: 1,
    denom: "NGS week",
    source: "NGS avg_cushion",
    startYear: 2016,
    zeroMass: "none",
  },
  {
    id: "adot",
    label: "Average Depth of Target",
    section: "NGS",
    kind: "continuous",
    higherIsBetter: true,
    format: "one_decimal",
    xMin: 0,
    xMax: 35,
    lowerBound: 0,
    minNBase: 3,
    denom: "targets",
    source: "receiving_air_yards / NGS IAY",
    startYear: 1999,
    zeroMass: "low",
  },
  {
    id: "catch_pct",
    label: "Catch %",
    section: "Efficiency",
    kind: "continuous",
    higherIsBetter: true,
    format: "percent",
    xMin: 0,
    xMax: 1,
    lowerBound: 0,
    upperBound: 1,
    minNBase: 3,
    denom: "targets",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "low",
  },
  {
    id: "target_share",
    label: "Target Share",
    section: "Share",
    kind: "continuous",
    higherIsBetter: true,
    format: "percent",
    xMin: 0,
    xMax: 0.5,
    lowerBound: 0,
    upperBound: 0.5,
    minNBase: 3,
    denom: "team targets",
    source: "target_share",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "air_yards_share",
    label: "Air Yards Share",
    section: "Share",
    kind: "continuous",
    higherIsBetter: true,
    format: "percent",
    xMin: 0,
    xMax: 0.6,
    lowerBound: 0,
    upperBound: 0.6,
    minNBase: 3,
    denom: "team air yards",
    source: "air_yards_share",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "wopr",
    label: "WOPR",
    section: "Share",
    kind: "continuous",
    higherIsBetter: true,
    format: "ratio",
    xMin: 0,
    xMax: 1,
    lowerBound: 0,
    minNBase: 3,
    denom: "targets",
    source: "wopr",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "racr",
    label: "RACR",
    section: "Efficiency",
    kind: "continuous",
    higherIsBetter: true,
    format: "ratio",
    xMin: 0,
    xMax: 3,
    lowerBound: 0,
    minNBase: 3,
    denom: "receiving air yards",
    source: "racr",
    startYear: 1999,
    zeroMass: "low",
  },
  {
    id: "receiving_epa",
    label: "Receiving EPA",
    section: "Efficiency",
    kind: "continuous",
    higherIsBetter: true,
    format: "one_decimal",
    xMin: -15,
    xMax: 20,
    minNBase: 3,
    denom: "targets",
    source: "receiving_epa",
    startYear: 1999,
    zeroMass: "low",
  },
  {
    id: "red_zone_targets",
    label: "Red Zone Targets",
    section: "Opportunity",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 10,
    binWidth: 1,
    minNBase: 1,
    denom: "games",
    source: "pbp",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "route_pct",
    label: "Route %",
    section: "Usage",
    kind: "continuous",
    higherIsBetter: true,
    format: "percent",
    xMin: 0,
    xMax: 1,
    lowerBound: 0,
    upperBound: 1,
    minNBase: 1,
    denom: "offensive snaps",
    source: "participation / ftn_charting",
    startYear: 2016,
    zeroMass: "med",
  },
  {
    id: "offensive_snap_pct",
    label: "Offensive Snap %",
    section: "Usage",
    kind: "continuous",
    higherIsBetter: true,
    format: "percent",
    xMin: 0,
    xMax: 1,
    lowerBound: 0,
    upperBound: 1,
    minNBase: 1,
    denom: "offensive snaps",
    source: "snap_counts",
    startYear: 2012,
    zeroMass: "low",
  },
];
