import type { StatDefinition } from "./types";

export const QB_STATS: StatDefinition[] = [
  {
    id: "cpoe",
    label: "CPOE",
    section: "Efficiency",
    kind: "continuous",
    higherIsBetter: true,
    format: "percent_pts",
    xMin: -25,
    xMax: 25,
    minNBase: 10,
    denom: "attempts",
    source: "player_stats.passing_cpoe",
    startYear: 1999,
    zeroMass: "low",
  },
  {
    id: "pacr",
    label: "PACR",
    section: "Efficiency",
    kind: "continuous",
    higherIsBetter: true,
    format: "ratio",
    xMin: 0,
    xMax: 3,
    lowerBound: 0,
    minNBase: 8,
    denom: "passing air yards",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "low",
  },
  {
    id: "passer_rating",
    label: "Passer Rating",
    section: "Efficiency",
    kind: "continuous",
    higherIsBetter: true,
    format: "rating",
    xMin: 0,
    xMax: 158.3,
    lowerBound: 0,
    upperBound: 158.3,
    minNBase: 10,
    denom: "attempts",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "low",
  },
  {
    id: "completion_pct",
    label: "Completion %",
    section: "Efficiency",
    kind: "continuous",
    higherIsBetter: true,
    format: "percent",
    xMin: 0,
    xMax: 1,
    lowerBound: 0,
    upperBound: 1,
    minNBase: 10,
    denom: "attempts",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "low",
  },
  {
    id: "passing_epa",
    label: "Passing EPA",
    section: "Efficiency",
    kind: "continuous",
    higherIsBetter: true,
    format: "one_decimal",
    xMin: -40,
    xMax: 40,
    minNBase: 8,
    denom: "attempts",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "low",
  },
  {
    id: "air_yards_diff",
    label: "Air Yards Differential",
    section: "NGS",
    kind: "continuous",
    higherIsBetter: true,
    format: "one_decimal",
    xMin: -10,
    xMax: 8,
    minNBase: 1,
    denom: "NGS week",
    source: "NGS",
    startYear: 2016,
    zeroMass: "none",
  },
  {
    id: "air_yards_to_sticks",
    label: "Air Yards to Sticks",
    section: "NGS",
    kind: "continuous",
    higherIsBetter: true,
    format: "one_decimal",
    xMin: -8,
    xMax: 8,
    minNBase: 1,
    denom: "NGS week",
    source: "NGS",
    startYear: 2016,
    zeroMass: "none",
  },
  {
    id: "expected_completion_pct",
    label: "Expected Completion %",
    section: "NGS",
    kind: "continuous",
    higherIsBetter: true,
    format: "percent",
    xMin: 0,
    xMax: 1,
    lowerBound: 0,
    upperBound: 1,
    minNBase: 1,
    denom: "NGS week",
    source: "NGS",
    startYear: 2016,
    zeroMass: "none",
  },
  {
    id: "aggressiveness",
    label: "Aggressiveness %",
    section: "NGS",
    kind: "continuous",
    higherIsBetter: true,
    format: "percent",
    xMin: 0,
    xMax: 1,
    lowerBound: 0,
    upperBound: 1,
    minNBase: 1,
    denom: "NGS week",
    source: "NGS aggressiveness",
    startYear: 2016,
    zeroMass: "low",
  },
  {
    id: "time_to_throw",
    label: "Time to Throw",
    section: "NGS",
    kind: "continuous",
    higherIsBetter: false,
    format: "seconds",
    xMin: 1.5,
    xMax: 6,
    lowerBound: 1.5,
    minNBase: 1,
    denom: "NGS pass attempts",
    source: "nextgen_stats passing",
    startYear: 2016,
    zeroMass: "none",
  },
  {
    id: "iay",
    label: "Intended Air Yards",
    section: "NGS",
    kind: "continuous",
    higherIsBetter: true,
    format: "one_decimal",
    xMin: 0,
    xMax: 25,
    lowerBound: 0,
    minNBase: 1,
    denom: "NGS week",
    source: "NGS passing",
    startYear: 2016,
    zeroMass: "none",
  },
  {
    id: "cay",
    label: "Completed Air Yards",
    section: "NGS",
    kind: "continuous",
    higherIsBetter: true,
    format: "one_decimal",
    xMin: 0,
    xMax: 20,
    lowerBound: 0,
    minNBase: 1,
    denom: "NGS week",
    source: "NGS passing",
    startYear: 2016,
    zeroMass: "none",
  },
  {
    id: "passing_tds",
    label: "Passing TDs",
    section: "Production",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 7,
    binWidth: 1,
    minNBase: 1,
    denom: "games with attempts",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "interceptions",
    label: "Interceptions",
    section: "Production",
    kind: "discrete",
    higherIsBetter: false,
    format: "count",
    xMin: 0,
    xMax: 7,
    binWidth: 1,
    minNBase: 1,
    denom: "games with attempts",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "sacks_taken",
    label: "Sacks Taken",
    section: "Production",
    kind: "discrete",
    higherIsBetter: false,
    format: "count",
    xMin: 0,
    xMax: 12,
    binWidth: 1,
    minNBase: 1,
    denom: "games with attempts",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "pass_attempts",
    label: "Pass Attempts",
    section: "Volume",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 70,
    binWidth: 1,
    minNBase: 8,
    denom: "attempts",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "completions",
    label: "Completions",
    section: "Volume",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 45,
    binWidth: 1,
    minNBase: 8,
    denom: "attempts",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "low",
  },
  {
    id: "passing_yards",
    label: "Passing Yards",
    section: "Volume",
    kind: "continuous",
    higherIsBetter: true,
    format: "yards",
    xMin: -10,
    xMax: 554,
    lowerBound: 0,
    minNBase: 8,
    denom: "attempts",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "deep_attempts",
    label: "Deep Attempts (20+)",
    section: "Volume",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 20,
    binWidth: 1,
    minNBase: 8,
    denom: "attempts",
    source: "passing_20",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "rush_attempts",
    label: "Rush Attempts",
    section: "Rushing",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 20,
    binWidth: 1,
    minNBase: 3,
    denom: "carries",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "rushing_yards",
    label: "Rushing Yards",
    section: "Rushing",
    kind: "continuous",
    higherIsBetter: true,
    format: "yards",
    xMin: -15,
    xMax: 150,
    lowerBound: 0,
    minNBase: 3,
    denom: "carries",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "rushing_tds",
    label: "Rushing TDs",
    section: "Rushing",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 4,
    binWidth: 1,
    minNBase: 3,
    denom: "carries",
    source: "player_stats",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "offensive_snap_pct",
    label: "Offensive Snap %",
    section: "Usage",
    kind: "continuous",
    higherIsBetter: true,
    format: "percent",
    xMin: 0,
    xMax: 1,
    lowerBound: 0,
    upperBound: 1,
    minNBase: 1,
    denom: "offensive snaps",
    source: "snap_counts",
    startYear: 2012,
    zeroMass: "low",
  },
];
