import type { StatDefinition } from "./types";

export const SECONDARY_STATS: StatDefinition[] = [
  {
    id: "interceptions",
    label: "Interceptions",
    section: "Ball",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 4,
    binWidth: 1,
    minNBase: 1,
    denom: "games",
    source: "def_interceptions",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "passes_defended",
    label: "Passes Defended",
    section: "Ball",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 6,
    binWidth: 1,
    minNBase: 1,
    denom: "games",
    source: "def_pass_defended",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "targets_allowed",
    label: "Targets Allowed",
    section: "Coverage",
    kind: "discrete",
    higherIsBetter: false,
    format: "count",
    xMin: 0,
    xMax: 18,
    binWidth: 1,
    minNBase: 2,
    denom: "targets allowed",
    source: "PFR def_targets",
    startYear: 2018,
    zeroMass: "med",
  },
  {
    id: "completions_allowed",
    label: "Completions Allowed",
    section: "Coverage",
    kind: "discrete",
    higherIsBetter: false,
    format: "count",
    xMin: 0,
    xMax: 15,
    binWidth: 1,
    minNBase: 2,
    denom: "targets allowed",
    source: "def_completions_allowed",
    startYear: 2018,
    zeroMass: "med",
  },
  {
    id: "receiving_yards_allowed",
    label: "Receiving Yards Allowed",
    section: "Coverage",
    kind: "continuous",
    higherIsBetter: false,
    format: "yards",
    xMin: 0,
    xMax: 250,
    lowerBound: 0,
    minNBase: 2,
    denom: "targets allowed",
    source: "def_yards_allowed",
    startYear: 2018,
    zeroMass: "med",
  },
  {
    id: "tds_allowed",
    label: "TDs Allowed",
    section: "Coverage",
    kind: "discrete",
    higherIsBetter: false,
    format: "count",
    xMin: 0,
    xMax: 3,
    binWidth: 1,
    minNBase: 2,
    denom: "targets allowed",
    source: "def_receiving_td_allowed",
    startYear: 2018,
    zeroMass: "high",
  },
  {
    id: "completion_pct_allowed",
    label: "Completion % Allowed",
    section: "Coverage",
    kind: "continuous",
    higherIsBetter: false,
    format: "percent",
    xMin: 0,
    xMax: 1,
    lowerBound: 0,
    upperBound: 1,
    minNBase: 4,
    denom: "targets allowed",
    source: "def_completion_pct",
    startYear: 2018,
    zeroMass: "low",
  },
  {
    id: "rating_allowed",
    label: "Passer Rating Allowed",
    section: "Coverage",
    kind: "continuous",
    higherIsBetter: false,
    format: "rating",
    xMin: 0,
    xMax: 158.3,
    lowerBound: 0,
    upperBound: 158.3,
    minNBase: 4,
    denom: "targets allowed",
    source: "def_passer_rating_allowed",
    startYear: 2018,
    zeroMass: "low",
  },
  {
    id: "adot_allowed",
    label: "aDOT Allowed",
    section: "Coverage",
    kind: "continuous",
    higherIsBetter: false,
    format: "one_decimal",
    xMin: 0,
    xMax: 30,
    lowerBound: 0,
    minNBase: 4,
    denom: "targets allowed",
    source: "def_adot",
    startYear: 2018,
    zeroMass: "none",
  },
  {
    id: "tackles_combined",
    label: "Tackles",
    section: "Tackles",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 16,
    binWidth: 1,
    minNBase: 1,
    denom: "games",
    source: "def_tackles_*",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "missed_tackles",
    label: "Missed Tackles",
    section: "Tackles",
    kind: "discrete",
    higherIsBetter: false,
    format: "count",
    xMin: 0,
    xMax: 7,
    binWidth: 1,
    minNBase: 1,
    denom: "games",
    source: "def_missed_tackles",
    startYear: 2018,
    zeroMass: "high",
  },
  {
    id: "defensive_snap_pct",
    label: "Defensive Snap %",
    section: "Usage",
    kind: "continuous",
    higherIsBetter: true,
    format: "percent",
    xMin: 0,
    xMax: 1,
    lowerBound: 0,
    upperBound: 1,
    minNBase: 1,
    denom: "defensive snaps",
    source: "snap_counts",
    startYear: 2012,
    zeroMass: "low",
  },
];
