import type { StatDefinition } from "./types";

export const KICKER_STATS: StatDefinition[] = [
  {
    id: "fg_attempts",
    label: "Field Goal Attempts",
    section: "Field goals",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 8,
    binWidth: 1,
    minNBase: 1,
    denom: "FGA",
    source: "fg_att",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "fg_made",
    label: "Field Goals Made",
    section: "Field goals",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 8,
    binWidth: 1,
    minNBase: 1,
    denom: "FGA",
    source: "fg_made",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "fg_pct",
    label: "Field Goal %",
    section: "Field goals",
    kind: "continuous",
    higherIsBetter: true,
    format: "percent",
    xMin: 0,
    xMax: 1,
    lowerBound: 0,
    upperBound: 1,
    minNBase: 1,
    denom: "FGA",
    source: "fg_pct",
    startYear: 1999,
    zeroMass: "low",
  },
  {
    id: "fg_long",
    label: "Longest Field Goal",
    section: "Field goals",
    kind: "discrete",
    higherIsBetter: true,
    format: "yards",
    xMin: 0,
    xMax: 70,
    binWidth: 5,
    minNBase: 1,
    denom: "FGA",
    source: "fg_long",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "fg_40_49",
    label: "FG Made 40–49",
    section: "Field goals",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 4,
    binWidth: 1,
    minNBase: 1,
    denom: "attempts in bucket",
    source: "fg_made_40_49",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "xp_attempts",
    label: "Extra Point Attempts",
    section: "Extra points",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 10,
    binWidth: 1,
    minNBase: 1,
    denom: "XPA",
    source: "pat_att",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "xp_made",
    label: "Extra Points Made",
    section: "Extra points",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 10,
    binWidth: 1,
    minNBase: 1,
    denom: "XPA",
    source: "pat_made",
    startYear: 1999,
    zeroMass: "med",
  },
];

export const PUNTER_STATS: StatDefinition[] = [
  {
    id: "punts",
    label: "Punts",
    section: "Punting",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 16,
    binWidth: 1,
    minNBase: 2,
    denom: "punts",
    source: "pt_att",
    startYear: 1999,
    zeroMass: "low",
  },
  {
    id: "gross_punt_yards",
    label: "Gross Punt Yards",
    section: "Punting",
    kind: "continuous",
    higherIsBetter: true,
    format: "yards",
    xMin: 0,
    xMax: 685,
    lowerBound: 0,
    minNBase: 2,
    denom: "punts",
    source: "pt_yards",
    startYear: 1999,
    zeroMass: "low",
  },
  {
    id: "net_punt_yards",
    label: "Net Punt Yards",
    section: "Punting",
    kind: "continuous",
    higherIsBetter: true,
    format: "yards",
    xMin: 0,
    xMax: 600,
    lowerBound: 0,
    minNBase: 2,
    denom: "punts",
    source: "pt_net_yards",
    startYear: 1999,
    zeroMass: "low",
  },
  {
    id: "inside_20",
    label: "Inside 20",
    section: "Punting",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 8,
    binWidth: 1,
    minNBase: 2,
    denom: "punts",
    source: "pt_inside_20",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "touchbacks",
    label: "Touchbacks",
    section: "Punting",
    kind: "discrete",
    higherIsBetter: false,
    format: "count",
    xMin: 0,
    xMax: 6,
    binWidth: 1,
    minNBase: 2,
    denom: "punts",
    source: "pt_touchback",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "fair_catches",
    label: "Fair Catches",
    section: "Punting",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 8,
    binWidth: 1,
    minNBase: 2,
    denom: "punts",
    source: "pt_fair_caught",
    startYear: 1999,
    zeroMass: "high",
  },
];

export const RETURNER_STATS: StatDefinition[] = [
  {
    id: "kick_returns",
    label: "Kick Returns",
    section: "Returns",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 11,
    binWidth: 1,
    minNBase: 1,
    denom: "returns",
    source: "kickoff_returns",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "punt_returns",
    label: "Punt Returns",
    section: "Returns",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 11,
    binWidth: 1,
    minNBase: 1,
    denom: "returns",
    source: "punt_returns",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "kick_return_yards",
    label: "Kick Return Yards",
    section: "Returns",
    kind: "continuous",
    higherIsBetter: true,
    format: "yards",
    xMin: -10,
    xMax: 305,
    lowerBound: 0,
    minNBase: 1,
    denom: "kick returns",
    source: "kick_return_yards",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "punt_return_yards",
    label: "Punt Return Yards",
    section: "Returns",
    kind: "continuous",
    higherIsBetter: true,
    format: "yards",
    xMin: -10,
    xMax: 200,
    lowerBound: 0,
    minNBase: 1,
    denom: "punt returns",
    source: "punt_return_yards",
    startYear: 1999,
    zeroMass: "med",
  },
  {
    id: "return_tds",
    label: "Return TDs",
    section: "Returns",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 2,
    binWidth: 1,
    minNBase: 1,
    denom: "returns",
    source: "pt_return_tds / special_teams_tds",
    startYear: 1999,
    zeroMass: "high",
  },
];
