"""
config.py — Colab shim (auto-generated by prepare_colab.py)

This mirrors clean/config.py but with Google Drive paths.
DO NOT EDIT — re-run prepare_colab.py to regenerate.
"""
from pathlib import Path

ACTIVE_MODEL = "v5"

# Paths resolve to Google Drive
ROOT         = Path(__file__).resolve().parent
DATA_DIR     = ROOT / "data"
MODEL_DIR    = Path("/content/drive/MyDrive/ballnet/v5/clean_download")
GATV2_SRC    = ROOT   # gatv2tcn.py lives in upload root

FEATURE_COLS    = ['PTS', 'AST', 'REB', 'TO', 'STL', 'BLK', 'PLUS_MINUS', 'TCHS', 'PASS', 'DIST', 'PACE', 'USG_PCT', 'TS_PCT']
PREDICTION_COLS = ['PTS', 'AST', 'REB', 'TO', 'STL', 'BLK']
PRED_INDICES    = [FEATURE_COLS.index(c) for c in PREDICTION_COLS]
SEQ_LENGTH      = 10

QUANTILE_REGRESSION = False
QUANTILES = [0.1, 0.5, 0.9]

SPLIT_TRAIN = 0.9
SPLIT_VAL   = 0.95
