import type { StatDefinition } from "./types";

export const OL_STATS: StatDefinition[] = [
  {
    id: "block_win_rate",
    label: "Block Win Rate",
    section: "Pass protection",
    kind: "continuous",
    higherIsBetter: true,
    format: "percent",
    xMin: 0,
    xMax: 1,
    lowerBound: 0,
    upperBound: 1,
    minNBase: null,
    denom: "pass snaps",
    source: "not in nflverse",
    startYear: null,
    zeroMass: "low",
    alwaysUnavailable: true,
  },
  {
    id: "pressures_allowed",
    label: "Pressures Allowed",
    section: "Pass protection",
    kind: "discrete",
    higherIsBetter: false,
    format: "count",
    xMin: 0,
    xMax: 12,
    binWidth: 1,
    minNBase: null,
    denom: "pass snaps",
    source: "not in nflverse",
    startYear: null,
    zeroMass: "high",
    alwaysUnavailable: true,
  },
  {
    id: "sacks_allowed",
    label: "Sacks Allowed",
    section: "Pass protection",
    kind: "discrete",
    higherIsBetter: false,
    format: "count",
    xMin: 0,
    xMax: 6,
    binWidth: 1,
    minNBase: null,
    denom: "pass snaps",
    source: "not in nflverse",
    startYear: null,
    zeroMass: "high",
    alwaysUnavailable: true,
  },
  {
    id: "penalties",
    label: "Penalties",
    section: "Discipline",
    kind: "discrete",
    higherIsBetter: false,
    format: "count",
    xMin: 0,
    xMax: 6,
    binWidth: 1,
    minNBase: 1,
    denom: "snap-weeks",
    source: "player_stats.penalties",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "penalty_yards",
    label: "Penalty Yards",
    section: "Discipline",
    kind: "discrete",
    higherIsBetter: false,
    format: "yards",
    xMin: 0,
    xMax: 50,
    binWidth: 5,
    minNBase: 1,
    denom: "snap-weeks",
    source: "penalty_yards",
    startYear: 1999,
    zeroMass: "high",
  },
  {
    id: "snap_pct",
    label: "Snap %",
    section: "Usage",
    kind: "continuous",
    higherIsBetter: true,
    format: "percent",
    xMin: 0,
    xMax: 1,
    lowerBound: 0,
    upperBound: 1,
    minNBase: 1,
    denom: "offensive snaps",
    source: "snap_counts.offense_pct",
    startYear: 2012,
    zeroMass: "low",
  },
  {
    id: "snaps_played",
    label: "Snaps Played",
    section: "Usage",
    kind: "discrete",
    higherIsBetter: true,
    format: "count",
    xMin: 0,
    xMax: 100,
    binWidth: 5,
    minNBase: 1,
    denom: "snap-weeks",
    source: "snap_counts",
    startYear: 2012,
    zeroMass: "low",
  },
];
