export type StatDescriptions = Record<string, string>;

/** Plain-language meaning of a stat, or undefined when the catalog has no entry. */
export function statDescription(statId: string): string | undefined {
  return STAT_DESCRIPTIONS[statId];
}

export const STAT_DESCRIPTIONS: StatDescriptions = {
  epa_per_dropback: "Expected Points Added (EPA) per dropback measures how much each pass attempt or sack changes the offense's expected points. Higher is better; positive means the passing game adds value on average.",
  cpoe: "Completion Percentage Over Expected (CPOE) is actual completion rate minus the rate expected for those throws. Higher is better; positive means the quarterback completes more passes than expected.",
  passing_td_rate: "Passing touchdown rate is passing touchdowns divided by pass attempts. Higher is better because a larger share of throws become touchdowns.",
  interception_rate: "Interception rate is interceptions thrown divided by pass attempts. Lower is better because fewer throws are turned over.",
  sack_rate: "Sack rate is sacks taken divided by dropbacks, where dropbacks are pass attempts plus sacks. Lower is better because the quarterback is sacked on fewer passing plays.",
  pacr: "Passing Air Conversion Ratio (PACR) is passing yards divided by passing air yards. Higher means more total passing yardage from the same air-yard volume, though play style and yards after catch affect it.",
  passer_rating: "NFL passer rating combines completion rate, yards per attempt, touchdown rate, and interception rate on a 0 to 158.3 scale. Higher is better; 158.3 is perfect.",
  completion_pct: "Completion percentage is completed passes divided by pass attempts. Higher is usually better, though throw difficulty and depth matter.",
  passing_epa: "Passing Expected Points Added (EPA) is the total change in expected points credited to a quarterback's passing plays. Higher is better, but totals also rise with more dropbacks.",
  air_yards_diff: "Air Yards Differential is average Completed Air Yards minus average Intended Air Yards. Higher values mean completions occur closer to the depth of the quarterback's typical attempts; context matters.",
  air_yards_to_sticks: "Air Yards to Sticks measures how far a quarterback's targets are, on average, beyond or short of the first-down marker. Positive means beyond the sticks; higher is more aggressive, not automatically better.",
  expected_completion_pct: "Expected Completion Percentage estimates how often a quarterback should complete his throws based on their difficulty. Higher means an easier or more favorable throw mix, not necessarily better quarterback play.",
  aggressiveness: "Aggressiveness is the share of pass attempts thrown into tight windows, with a defender within 1 yard of the receiver at the catch point or incompletion. Higher means more tight-window throws, not necessarily better.",
  time_to_throw: "Time to Throw is the average seconds from snap to pass release, excluding sacks. Lower means a quicker release; higher means the quarterback holds the ball longer, so neither direction is always better.",
  iay: "Intended Air Yards (IAY) is the average distance downfield of all pass attempts. Higher means deeper throws on average; it describes style more than quality.",
  cay: "Completed Air Yards (CAY) is the average distance downfield traveled by completed passes before the catch. Higher means completions are occurring farther downfield; it is not purely a quality measure.",
  passing_tds: "Passing touchdowns are touchdown passes thrown. Higher is better, though the total depends heavily on passing volume and scoring opportunities.",
  interceptions: "Interceptions depend on position: for quarterbacks, they are passes thrown to defenders and lower is better; for defenders, they are passes caught from the offense and higher is better.",
  sacks_taken: "Sacks taken count passing plays on which the quarterback is tackled behind the line before throwing. Lower is better, though protection, scheme, and quarterback style all matter.",
  pass_attempts: "Pass attempts count official throws by the quarterback. More attempts mean more passing volume, not necessarily better efficiency.",
  completions: "Completions count pass attempts successfully caught by an eligible receiver. Higher means more completed passes, but the total is strongly driven by volume.",
  passing_yards: "Passing yards are the total yards gained on completed passes, including yards after the catch. Higher is better production, but totals depend on passing volume.",
  passing_20_plus: "Number of completed passes that gain at least 20 yards. Higher means more explosive passing plays, not necessarily more 20-plus-air-yard attempts.",
  rush_attempts: "Rush attempts are official carries. Higher means more rushing volume and workload, not necessarily better rushing efficiency.",
  rushing_yards: "Rushing yards are the total yards gained on carries. Higher is better production, but totals depend heavily on rushing volume.",
  rushing_tds: "Rushing touchdowns are touchdowns scored on carries. Higher is better, though the total depends on goal-line usage and rushing volume.",
  offensive_snap_pct: "Offensive Snap Percentage is the share of a team's offensive snaps the player is on the field for. Higher means a larger role and more opportunity, not necessarily better performance.",
  epa_per_rush: "Expected Points Added (EPA) per rush measures the average change in the offense's expected points on a player's carries. Higher is better; positive means the runs add value on average.",
  ryoe: "Rushing Yards Over Expected per Attempt (RYOE/Att) is actual rushing yards minus Next Gen Stats expected yards, averaged per carry. Higher is better; positive means the runner gains more than expected.",
  rushing_epa: "Rushing Expected Points Added (EPA) is the total change in expected points on a player's carries. Higher is better, but totals also increase with more rushing volume.",
  ryoe_total: "Rushing Yards Over Expected (RYOE) is total actual rushing yards minus total expected rushing yards across a player's carries. Higher is better; positive means the runner beat expectation overall.",
  yards_per_carry: "Yards per carry is rushing yards divided by rush attempts. Higher is better, though big plays, blocking, and game situation can move it sharply.",
  yac_per_carry: "Yards After Contact per Carry is rushing yards gained after first defender contact divided by carries. Higher is generally better and indicates more yardage created after contact.",
  broken_tackle_rate: "Broken tackle rate is broken tackles divided by carries. Higher is generally better because the runner escapes or runs through defenders more often.",
  yards_after_contact: "Yards After Contact is total rushing yardage gained after first contact from a defender. Higher is generally better, but the total also depends on carry volume.",
  broken_tackles: "Broken tackles count times the runner makes a significant move to get past or through a defender. Higher is generally better, but more carries create more chances.",
  ngs_efficiency: "Next Gen Stats Rushing Efficiency is total distance traveled by the ball carrier divided by rushing yards gained. Lower is more direct north-south running; higher means more lateral or extra movement.",
  expected_rush_yards: "Expected Rush Yards is the total yardage Next Gen Stats predicts from the player's rushing opportunities using tracking data for all players. Higher means more favorable opportunities, not better runner performance.",
  time_to_los: "Time to Line of Scrimmage is the average time a runner spends behind the line before crossing it. Lower means getting downhill sooner; higher can reflect patience or hesitation, so lower is not always better.",
  eight_plus_defenders_pct: "8+ Defenders Percentage is the share of carries faced with at least eight defenders in the box at the snap. Lower usually means lighter boxes; it describes defensive attention more than runner skill.",
  fumbles: "Fumbles here counts fumbles on rushing plays, whether or not the defense recovers them. Lower is better.",
  targets: "Targets count passes thrown toward the player. Higher means more receiving opportunity, not necessarily better efficiency.",
  receptions: "Receptions are completed passes caught by the player. Higher means more receiving production and usage, though volume drives the total.",
  receiving_yards: "Receiving yards are total yards gained on catches, including yards after the catch. Higher is better production, but totals depend on targets and receptions.",
  target_share: "Target share is the player's targets divided by the team's total targets. Higher means a larger share of the passing offense and usually more fantasy opportunity.",
  wopr: "Weighted Opportunity Rating (WOPR) combines target share and air-yards share, weighting target share more heavily. Higher means a larger, more valuable receiving role.",
  red_zone_touches: "Red-zone touches count carries plus receptions inside the opponent's 20-yard line. Higher is better for scoring opportunity, especially in fantasy football.",
  expected_fantasy_points: "Expected Fantasy Points estimates how many fantasy points an average player would score from the same opportunities and game situations. Higher means a more valuable workload.",
  epa_per_target: "Expected Points Added (EPA) per target measures the average change in the offense's expected points when the receiver is targeted. Higher is better and reflects efficient targets.",
  yards_per_target: "Yards per target is receiving yards divided by targets. Higher is better efficiency, combining catch rate, target depth, and yards after catch.",
  receiving_td_rate: "Receiving touchdown rate is receiving touchdowns divided by targets. Higher is better because a larger share of targets become touchdowns.",
  drop_rate: "Drop rate is drops divided by targets. Lower is better because fewer targeted passes are dropped.",
  receiving_epa: "Receiving Expected Points Added (EPA) is the total change in expected points on plays where the player is targeted. Higher is better, but totals also depend on target volume.",
  racr: "Receiver Air Conversion Ratio (RACR) is receiving yards divided by receiving air yards. Higher means the receiver turns the same air-yard opportunity into more actual yards.",
  catch_pct: "Catch percentage is receptions divided by targets. Higher is usually better, though target difficulty and depth strongly affect it.",
  yac_oe: "Yards After Catch Over Expected (YACOE) is actual average yards after catch minus Next Gen Stats expected YAC. Higher is better; positive means the receiver creates more after the catch than expected.",
  avg_yac: "Average Yards After Catch (YAC) is the average yardage gained after each reception. Higher is generally better and reflects what happens after the ball is caught.",
  expected_yac: "Expected Yards After Catch (xYAC) estimates how many yards a receiver should gain after the catch from tracking data such as speed, separation, and defender locations. Higher means a more favorable catch situation.",
  yac: "Yards After Catch (YAC) is total receiving yardage gained after the catch. Higher is better production, but the total depends on how many passes are caught.",
  separation: "Separation is the average distance between the receiver and the nearest defender at the catch point or incompletion. Higher usually means the receiver is more open when the target arrives.",
  cushion: "Cushion is the average distance between the receiver and the defender lined up across from him at the snap on targeted plays. Higher means the defender starts farther off; it is not purely a receiver-skill metric.",
  adot: "Average Depth of Target (aDOT) is the average distance downfield of a player's targets. Higher means a deeper target profile; it measures role and style more than quality.",
  receiving_tds: "Receiving touchdowns are touchdown catches. Higher is better, though the total depends on targets and scoring opportunities.",
  drops: "Drops are catchable targeted passes the receiver fails to secure according to the charting source. Lower is better.",
  air_yards_share: "Air Yards Share is the player's receiving air yards divided by the team's total receiving air yards. Higher means a larger share of the offense's downfield opportunity.",
  red_zone_targets: "Red-zone targets are passes thrown to the player inside the opponent's 20-yard line. Higher means more high-value scoring opportunities.",
  route_pct: "Route Percentage is the share of team dropbacks on which the player runs a pass route. Higher means the player is available as a receiver more often and usually has more target opportunity.",
  block_win_rate: "Block Win Rate is the share of pass-blocking snaps graded as successful. Higher is better, but the exact win standard varies by data provider; this metric is currently unavailable here.",
  pressures_allowed: "Pressures Allowed counts pass-blocking snaps on which the lineman gives up pressure on the quarterback. Lower is better; this metric is currently unavailable here.",
  sacks_allowed: "Sacks Allowed counts sacks attributed to the lineman's pass protection. Lower is better; this metric is currently unavailable here.",
  penalties: "Penalties count accepted penalties charged to the player. Lower is better because penalties cost the offense yards or favorable situations.",
  penalty_yards: "Penalty Yards are the total yards assessed on penalties charged to the player. Lower is better.",
  snap_pct: "Snap Percentage is the share of the team's offensive snaps the lineman plays. Higher means more playing time and availability, not necessarily better blocking.",
  snaps_played: "Snaps Played is the number of offensive plays the lineman is on the field for. Higher means more playing time, not necessarily better performance.",
  pressures: "Pressures count quarterback pressures from hurries, knockdowns, and sack plays. Higher is generally better because the defender disrupts the passer more often.",
  qb_hits: "Quarterback Hits count times the defender hits the quarterback after a pass play without recording a sack. Higher is generally better and shows pass-rush disruption.",
  hurries: "Hurries count plays where the defender pressures the quarterback into throwing earlier or under greater stress. Higher is generally better.",
  sacks: "Sacks count times the defender tackles the quarterback behind the line on a passing play. Higher is better.",
  tackles_for_loss: "Tackles for Loss count tackles that stop the ball carrier behind the line of scrimmage. Higher is generally better.",
  missed_tackle_rate: "Missed tackle rate is missed tackles divided by total tackle chances. Lower is better because the defender finishes a larger share of tackle opportunities.",
  missed_tackles: "Missed tackles count plays where the defender had a reasonable chance to bring down the ball carrier but failed. Lower is better, though more tackle chances can raise the total.",
  tackles_combined: "Combined tackles are solo tackles plus assisted tackles. Higher shows more tackling production, though role, snap volume, and where a player lines up strongly affect the total.",
  tackles_solo: "Solo tackles are tackles credited to one defender without an assist. Higher shows more individual tackling production, though snap volume and role matter.",
  tackles_ast: "Assisted tackles are tackles where the player helps another defender make the stop. Higher shows more involvement in tackles, though role and snap volume matter.",
  forced_fumbles: "Forced fumbles count times the defender causes the ball carrier to lose possession of the ball, whether or not the defense recovers it. Higher is better.",
  defensive_snap_pct: "Defensive Snap Percentage is the share of the team's defensive snaps the player is on the field for. Higher means a larger role and more opportunity, not necessarily better performance.",
  rating_allowed: "Passer Rating Allowed is the NFL passer rating produced on throws targeting the defender's coverage. Lower is better; 158.3 is the worst possible perfect passer rating for the offense.",
  yards_per_target_allowed: "Yards per Target Allowed is receiving yards surrendered divided by targets into the defender's coverage. Lower is better.",
  completion_pct_allowed: "Completion Percentage Allowed is completions surrendered divided by targets into the defender's coverage. Lower is generally better.",
  td_rate_allowed: "Touchdown Rate Allowed is receiving touchdowns surrendered divided by targets into the defender's coverage. Lower is better.",
  adot_allowed: "Average Depth of Target Allowed is how far downfield the defender is targeted on average. Higher means opponents challenge deeper; lower means shorter targets, so neither direction is inherently better.",
  tds_allowed: "Touchdowns Allowed counts receiving touchdowns surrendered while the defender is the primary coverage player. Lower is better.",
  receiving_yards_allowed: "Receiving Yards Allowed is the total receiving yardage surrendered on targets into the defender's coverage. Lower is better, but target volume matters.",
  completions_allowed: "Completions Allowed counts completed passes surrendered on targets into the defender's coverage. Lower is better, though target volume matters.",
  targets_allowed: "Targets Allowed counts passes thrown at the defender's coverage assignment. Lower can mean fewer chances or greater avoidance, so it is not a pure coverage-quality measure.",
  passes_defended: "Passes Defended count passes the defender breaks up or otherwise prevents from being completed. Higher is generally better, though more targets create more chances.",
  fg_pct: "Field Goal Percentage is field goals made divided by field goal attempts. Higher is better.",
  fg_made: "Field Goals Made counts successful field goal attempts. Higher is better scoring production, but opportunity depends on the offense.",
  fg_attempts: "Field Goal Attempts count field goals the kicker tries. Higher means more kicking opportunity, not necessarily better kicking.",
  fg_long: "Longest Field Goal is the distance of the kicker's longest made field goal. Higher shows greater demonstrated range, though opportunity and conditions matter.",
  fg_40_49: "Field Goals Made from 40 to 49 yards counts successful kicks from that distance range. Higher is better production, but attempts in that range drive the total.",
  xp_made: "Extra Points Made counts successful point-after-touchdown kicks. Higher is better scoring production, but team touchdown volume drives the opportunities.",
  xp_attempts: "Extra Point Attempts count point-after-touchdown kicks attempted. Higher means more opportunities created by the offense, not better kicking.",
  net_punt_yards: "Net Punt Yards are total punting yards after subtracting return yardage and touchback costs. Higher means more total field position flipped, but the total also depends on punt volume.",
  inside_20_rate: "Inside-20 Rate is the share of punts downed or fielded inside the opponent's 20-yard line. Higher is generally better because more punts pin the opponent deep.",
  touchback_rate: "Touchback Rate is the share of punts that become touchbacks. Lower is generally better because touchbacks erase some field-position value, though punt location matters.",
  fair_catch_rate: "Fair Catch Rate is the share of punts fielded with a fair catch. Higher often means fewer return chances, but it also depends on punt location and coverage.",
  gross_to_net_loss: "Gross-to-Net Yardage Loss is gross punt yards minus net punt yards, divided by punts. Lower is better because less yardage is lost to returns and touchbacks.",
  gross_punt_yards: "Gross Punt Yards are total yards the ball travels on punts before return and touchback adjustments. Higher means more total punt distance, but the total is volume-driven.",
  inside_20: "Inside 20 counts punts that finish inside the opponent's 20-yard line. Higher is generally better field-position production, but more punts create more chances.",
  fair_catches: "Fair Catches count punts on which the returner signals a fair catch. Higher can indicate strong hang time and coverage, but the total is also driven by punt volume and location.",
  touchbacks: "Touchbacks count punts that enter the end zone and are ruled touchbacks. Lower is generally better when trying to pin opponents deep, though opportunity and punt location matter.",
  punts: "Punts count punt attempts. Higher means more punting volume, usually reflecting team game situation rather than punter quality.",
  kick_return_yards: "Kick Return Yards are total yards gained on kickoff returns. Higher means more return production, but the total depends heavily on return opportunities.",
  punt_return_yards: "Punt Return Yards are total yards gained on punt returns. Higher means more return production, but the total depends heavily on return opportunities.",
  return_tds: "Return Touchdowns count touchdowns scored on kick or punt returns. Higher is better.",
  kick_returns: "Kick Returns count kickoffs the player returns. Higher means more return volume and opportunity, not necessarily better efficiency.",
  punt_returns: "Punt Returns count punts the player returns. Higher means more return volume and opportunity, not necessarily better efficiency.",
};
